### ISSUE TITLE
请问是不支持laravel9吗？

### ISSUE THREAD

**Issue by 2515104337** [chowjiawei/laravel-help-plugin#2]
composer 安装提示这个错误：

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires chowjiawei/laravel-help-plugin ^1.5 -> satisfiable by chowjiawei/laravel-help-plugin[v1.5.3].
    - chowjiawei/laravel-help-plugin v1.5.3 requires laravel/framework ^6.0|^7.0|^8.0 -> found laravel/framework[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.19).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by chowjiawei** [comment]
现在支持了laravel 9 可以下载 1.5.4版本体验
